### ISSUE TITLE
how to arrange data in data dir for test_pretrained？

### ISSUE THREAD

**Issue by l9761116** [edwardzhou130/Panoptic-PolarNet#12]
I want to do inference on some sequence. Since the space on my server is limited and I cannot even download the 80G velodyne data zip, so I copied labels and velodyne data of sequence 00 from other's server and put it in data/sequences/00.
I run 'python test_pretrained.py'. But the results all showed 0.00.
My velodyne dir is : /data/sequences/00/velodyne. The labels dir is: /data/sequences/00/labels.
Part of the returned results are the follows:
'''
0it [00:00, ?it/s]
Current val PQ is 0.000
Current val miou is 0.000
Inference time per 1 is nan seconds, postprocessing time is nan seconds per scan
'''
Does anyone know if I put the data wrongly or something?
Also, is it possible that I do inference on raw point cloud data?

**Comment by edwardzhou130** [comment]
Validation set is 08. But you can change it in here: https://github.com/edwardzhou130/Panoptic-PolarNet/blob/3a72f2380a4e505e191b69da596f521a9d9f1a71/semantic-kitti.yaml#L207-L232

**Comment by l9761116** [comment]
> Validation set is 08. But you can change it in here:
> 
> https://github.com/edwardzhou130/Panoptic-PolarNet/blob/3a72f2380a4e505e191b69da596f521a9d9f1a71/semantic-kitti.yaml#L207-L232

Thanks!
