### ISSUE TITLE
What do labels like 131073, 65537 and 917505 mean

### ISSUE THREAD

**Issue by l9761116** [edwardzhou130/Panoptic-PolarNet#14]
I notice that in the prediction results there are these very big labels.
I load the label file (predicted result) with 
>>>label = np.fromfile(label_path, dtype=np.uint32, count=-1).reshape([-1,1])

**Comment by edwardzhou130** [comment]
Each label is an int32 number where the upper half stores the instance id and the lower half stores the semantic label. https://github.com/edwardzhou130/Panoptic-PolarNet/blob/3a72f2380a4e505e191b69da596f521a9d9f1a71/dataloader/dataset.py#L64-L66

**Comment by l9761116** [comment]
> 
If I get it right, I can get the labels with the code:
```python3
labels = np.fromfile(label_path, dtype=np.uint32, count=-1).reshape([-1,1])
labels = labels & 0xFFFF
labels = np.vectorize(self.learning_map.__getitem__)(labels)
```
Is it so?
