### ISSUE TITLE
Check Occlusion in Data Augmentation

### ISSUE THREAD

**Issue by thomas-enxuli** [edwardzhou130/Panoptic-PolarNet#3]
Thanks for your contribution and your work is very impressive and interesting. Just wondering about the `check_occlusion` function in the part of instance augmentation ( https://github.com/edwardzhou130/Panoptic-PolarNet/blob/main/dataloader/instance_augmentation.py#L160 ). The goal of this function is to check whether a point is within a (2 metre) range of any point in a point cloud right? Would `dist = np.linalg.norm(points-center,axis=0)` be `dist = np.linalg.norm(points-center,axis=1)` instead? When you compute norm on axis 0, it will be a shape of (3, ) for [x, y, z], and on axis 1 will be a shape of (N, ) for number of points.

**Comment by edwardzhou130** [comment]
Yes, you are right. ``axis`` should be 1 to get the correct distances. I'll commit a fix for this. Thanks for the report.
